### ISSUE TITLE
1 - Visual Enhancement

### ISSUE THREAD

**Issue by nachitodev** [xKenyh/ip-lookup#1]
# Text Errors [Fixed]

![image](https://user-images.githubusercontent.com/67612701/121039971-eae01b00-c787-11eb-8e67-0dd8c3b29a58.png)
![image](https://user-images.githubusercontent.com/67612701/121039992-f16e9280-c787-11eb-9951-3b2441e3ae62.png)

# Make this text smaller, it is not comfortable [Fixed]
![image](https://user-images.githubusercontent.com/67612701/121040681-79ed3300-c788-11eb-8228-83bc5e6f2ef0.png)

# Invisible button 
![image](https://user-images.githubusercontent.com/67612701/121041385-144d7680-c789-11eb-9ba7-a169e50bf1d0.png)

# Where is Re=L.csproj ? [Fixed] 

![image](https://user-images.githubusercontent.com/67612701/121042394-064c2580-c78a-11eb-8f11-476cb25faccf.png)

# Github Repository Enhancement

_Remove Packages, Provide a Description and add a Release Option._

**Comment by nicolascarlino** [comment]
This is because you don't have the font that im using, i will upload it right now

**Comment by nachitodev** [comment]
Check This! 

[Install A Font with C#](https://stackoverflow.com/questions/21986744/how-to-install-a-font-programmatically-c)

**Comment by nicolascarlino** [comment]
Fixed tonight
