### ISSUE TITLE
💀 

### ISSUE THREAD

**Issue by enit9747** [xKenyh/ip-lookup#2]
bro didnt even parse the json 😭

**Comment by nachitodev** [comment]
stfu
![image](https://user-images.githubusercontent.com/67612701/157164284-a22a9c89-2d98-497f-bc1a-7d7c906890cd.png)

**Comment by nicolascarlino** [comment]
the variable "ip" is literally the parsed json.

**Comment by enit9747** [comment]
then he mustve somehow still fucked up cuz its not properly parsed

**Comment by nicolascarlino** [comment]
is good parsed, if not, do a pull request then.
